### ISSUE TITLE
Fix for the TomTom routeplanner functionality

### ISSUE THREAD

**Issue by rijnb** [MSBilgin/OnlineRoutingMapper#3]
The TomTom route planner functionality is broken: it display the locations of the spoken instructions. 
What you really want is a polyline from the route itself. Those locations are in a different portion of the JSON response.

Here are 2 code changes you need to make in to `routeprovider.py` file:

line 34 - remove most options from the URL, they are not required:

    self.__tomtomBaseURL__ = 'https://api.tomtom.com/routing/1/calculateRoute/%s:%s/jsonp?key=hpygzp67548xfpk69qsfwqng&traffic=false'

and line 208 - read from `routes[0].legs[0]`, not `instructions`:

    elif self.__serviceType__ == 5: #tomtom JSON
      responseData = json.loads(response[9:-1])
      coors = responseData['routes'][0]['legs'][0]['points']
      usefulCoorList = []
        for i in coors:
        usefulCoorList.extend([i['longitude'], i['latitude']])
      return self.__coorOrganizer__(usefulCoorList)

**Update:** This fix is also supplied as a pull request

**Comment by MSBilgin** [comment]
Thank you for warning me. I will commit your PR. Also there are some API changes on other providers. After updating all i 'll send new version to QGIS community.
